# Generated by Django 4.2 on 2023-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProvideGasMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("national_identity_card_number", models.IntegerField(max_length=14)),
                (
                    "national_identity_card_photo",
                    models.ImageField(upload_to="static/images"),
                ),
                (
                    "copy_of_the_ownership_contract",
                    models.ImageField(upload_to="static/images"),
                ),
                (
                    "photo_of_recent_electricity_receipt",
                    models.ImageField(upload_to="static/images"),
                ),
                (
                    "receipt_of_approval_from_gas_company",
                    models.ImageField(upload_to="static/images"),
                ),
                (
                    "origin_type",
                    models.CharField(
                        choices=[
                            ("شقة سكنية", "شقة سكنية"),
                            ("فيلا", "فيلا"),
                            ("مجمع سكني", "مجمع سكني"),
                            ("مكتب", "مكتب"),
                            ("مستودع", "مستودع"),
                            ("اختر من القائمة التالية", "اختر من القائمة التالية"),
                        ],
                        default="اختر من القائمة التالية",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
