# Generated by Django 4.2 on 2023-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GasBills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providegasmeter",
            name="national_identity_card_number",
            field=models.CharField(max_length=14),
        ),
    ]
